project:
  type: book
  output-dir: docs
  preview:
    watch-inputs: false

book:
  title: "Secure Multiparty Computation Meets Deep Learning"
  author: "Yoshi234"
  date: "1/30/2024"
  chapters:
    - index.qmd
    - part: secure_primitives.qmd
      chapters:
        - secure_prim/beavers_triples.qmd
        - secure_prim/oblivious_transfer.qmd
        - secure_prim/one_way_functions.qmd
        - secure_prim/crypten.qmd
    - part: deep_learning.qmd
      chapters:
        -  deeplearn/deep_primitives/RNNs.qmd
        -  deeplearn/deep_primitives/word_embeddings.qmd
        -  deeplearn/deep_primitives/residual_connection.qmd
        -  object_detection.qmd
        -  deeplearn/_objdet_impl.qmd
        -  deeplearn/_addernet.qmd
    - part: v2x_apps.qmd
      chapters:
        - red_light.qmd
        - traffic_flow.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    html-math-method: katex
    toc-depth: 5
    number-depth: 5
    theme: darkly
  pdf:
    documentclass: scrreprt


