project:
  type: book
  output-dir: docs

book:
  title: "Secure Multiparty Computation Meets Deep Learning"
  author: "Yoshi234"
  date: "1/30/2024"
  chapters:
    - index.qmd
    - object_detection.qmd
    - red_light.qmd
    - traffic_flow.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt



