project:
  type: book
  output-dir: docs

book:
  title: "Secure Multiparty Computation Meets Deep Learning"
  author: "Yoshi234"
  date: "1/30/2024"
  chapters:
    - index.qmd
    - part: secure_primitives.qmd
      chapters:
        - secure_prim/beavers_triples.qmd
        - secure_prim/oblivious_transfer.qmd
    - part: deep_learning.qmd
      chapters:
        -  deeplearn/deep_primitives/residual_connection.qmd
        -  object_detection.qmd
    - part: v2x_apps.qmd
      chapters:
        - red_light.qmd
        - traffic_flow.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc-depth: 5
    number-depth: 5
    theme: darkly
  pdf:
    documentclass: scrreprt



