### Random Oblivious Transfer (ROT)

> what is the difference between $ROT_{l}^{m}$ and $OT_{l}^{m}$?

Random Oblivious Transfer is the most general form of OT. In this setting, we
assume that there are two parties involved: Alice and Bob. Here, Alice functions
as the *sender* and Bob functions as the *receiver*. Additionally, we assume
a 1-out-of-2 ROT functionality.
Alice and Bob follow the $ROT_{m}^{l}$ protocol below:

*The receiver (Bob) provides its selection bit* $b$ *to the protocol, and*
*two random strings are generated by the ROT protcol. These are* $r_{0}$ and $r_{1}$,
*one of which corresponds to the input bit* $b$.
*The protocol provides these two random strings to the sender, and provides*
*the receiver with a bit* $r_{b} \in \{r_{0},r_{1}\}$ *which corresponds to 
*the receiver's selection bit*.

> How are bits selected by the protocol without assistance of a TTP?

**Case 1: Bob uses the same selection bit** $b$

Once the random outputs have been generated for Alice and Bob, they 
collectively perform an instance of ${2 \choose 1}\text{-OT}$.

1. Alice inputs chosen bits $(x_{0}, x_{1})$ and Bob inputs selection bit $b$
2. Alice sends to Bob $(x_{0} \oplus r_{0}, x_{1} \oplus r_{1})$
3. Bob performs $(x_{b} \oplus r_{b}) \oplus r_{b}$ to obtain $x_{b}$

Here, only one message is passed from Alice to Bob $S \rightarrow R$

**Case 2: Bob chooses a different selection bit** $c$

1. Bob sends to Alice $k = b \oplus c$ where $b$ was the chosen bit input
   to the $ROT$ protocol, and $c$ is the chosen bit of the ${2\choose 1}\text{-OT}$ 
2. Alice permutes $k$ with $r_{0}$ and $r_{1}$ to get $r_{k}$ and $r_{\overline{k}}$.
3. Alice sends $(y_{0}, y_{1}) = (x_{0} \oplus r_{k}, x_{1} \oplus r_{\overline{k}})$ to
   Bob
4. Bob performs $y_{c} \oplus r_{b}$ to obtain $x_{c}$